### ISSUE TITLE
Profiles page parameters can be updated.

### ISSUE THREAD

**Issue by cantucer** [CankutBoraTuncer/Alicisindan#19]
The username on profiles page can be set to something like "Guest" when no user is logged in.

This might be helpful as it is hard to see either if you are logged in or not atm.

**Comment by cantucer** [comment]
Not fixed

**Comment by EmirhanYagcioglu** [comment]
@begumfilizoz fix has been reimplemented. It got somehow lost after merges. Now it is working again.
